fisinos/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    # path("accounts/", include("accounts.urls")),
    path("accounts/", include("allauth.urls")),
    path("", include("main.urls")),
]

main/urls.py
from django.urls import path

from . import views

app_name = "main"

urlpatterns = [
    path("", views.homepage, name="homepage"),
    path("topics/", views.topics, name="topics"),
    path("profile/", views.update_profile, name="profile"),
]

main/models.py
import datetime

from django.contrib import admin
from django.contrib.auth.models import User
from django.contrib.auth.signals import user_logged_in
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone

# Create your models here.

# Create topics that can be suscribed by users


class Topic(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    suscribers = models.ManyToManyField(User, related_name="topics", blank=True)

    def __str__(self):
        return self.name


# Create announcements that can be suscribed by users by topics
# announcements can have multiple topics
# and can be suscribed by multiple users


class Announcement(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    topics = models.ManyToManyField(Topic, related_name="announcements")
    # users = models.ManyToManyField(User, related_name='announcements')
    pub_date = models.DateTimeField("date published", default=timezone.now)

    def __str__(self):
        return self.title

    @admin.display(
        boolean=True,
        ordering="pub_date",
        description="Published recently?",
    )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    def topics_list(self):
        # sort topics by name
        return ", ".join([topic.name for topic in self.topics.all().order_by("name")])

    def get_topics(self):
        return self.topics.all()


# Create users profile that can suscribe to announcements by topics
# users can be retrieved from the django auth user model
# users can have multiple topics suscribed


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    topics = models.ManyToManyField(Topic, related_name="users")

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.userprofile.save()


# detect when a user logs in and has no user profile
@receiver(user_logged_in)
def user_logged_in_callback(sender, request, user, **kwargs):
    if not hasattr(user, "userprofile"):
        UserProfile.objects.create(user=user)

notify/models.py
from django.db import models

# Create your models here.

main/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Announcement, Topic, UserProfile


# Multiple choice froms showing the topics the user can subscribe to
class TopicForm(forms.Form):
    topics = forms.ModelMultipleChoiceField(
        queryset=Topic.objects.all(), widget=forms.CheckboxSelectMultiple
    )

    class Meta:
        model = UserProfile
        fields = ("topics",)


# Form that allows users to change their name and email
class UserForm(forms.ModelForm):
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={"readonly": "readonly"}), required=False
    )

    class Meta:
        model = User
        fields = ("first_name", "last_name", "email")


# Form that allows users to change their profile information
class ProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ("topics",)

main/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import redirect, render

from .forms import ProfileForm, TopicForm, UserForm
from .models import Announcement, Topic, UserProfile

# Create your views here.


def homepage(request):
    latest_announcements_list = Announcement.objects.order_by("-pub_date")[:5]
    context = {"latest_announcements_list": latest_announcements_list}
    return render(request, "main/home.html", context)


# topics can receive a POST with user topics suscriptions
# topics can receive a GET with all topics and user topics suscriptions
def topics(request):
    if request.method == "POST":
        form = TopicForm(request.POST)
        if form.is_valid():
            # set the user topics
            user = UserProfile.objects.get(user=request.user)
            user.topics.set(form.cleaned_data["topics"])
            user.save()
            return redirect("main:homepage")
    else:
        # get the user topics and mark them as selected
        user = UserProfile.objects.get(user=request.user)
        form = TopicForm(initial={"topics": user.topics.all()})
    return render(request, "main/topics.html", {"form": form})


def update_profile(request):
    if request.method == "POST":
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, instance=request.user.userprofile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, "Your profile was successfully updated!")
            return redirect("main:homepage")
        else:
            messages.error(request, "Please correct the error below.")
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.userprofile)
    return render(
        request,
        "main/profile.html",
        {"user_form": user_form, "profile_form": profile_form},
    )

notify/views.py
from django.shortcuts import render

# Create your views here.

main/templates/main/home.html
{% extends 'header.html' %}

{% block title %}Home{% endblock %}

{% block content %}

<div class="container py-5">

    {% if latest_announcements_list %}
    <h2>Últimos anuncios</h2>
    <div class="card-deck">
        {% for announcement in latest_announcements_list %}
        <div class="card bg-light border-dark mb-3">
            <div class="card-header">{{ announcement.pub_date }}</div>
            <div class="card-body">
                <h5 class="card-title">{{ announcement.title }}</h5>
                <p class="card-text">{{ announcement.description }}</p>
            </div>
            <div class="card-footer">
                <small class="text-muted">{{ announcement.topics_list }}</small>
            </div>
        </div>

        {% endfor %}
    </div>
    {% else %}
    <p>No announcements are available.</p>
    {% endif %}

</div>

{% endblock %}

main/templates/main/profile.html
{% extends 'header.html' %}

{% block title %}Home{% endblock %}

{% block content %}

{% load crispy_forms_tags %}

<div class="container py-5">
    <form method="post">
        {% csrf_token %}
        {{ user_form|crispy }}
        {{ profile_form|crispy }}
        <button type="submit">Save changes</button>
    </form>
</div>

{% endblock %}

main/templates/main/topics.html
{% extends 'header.html' %}

{% block title %}Topics{% endblock %}

{% block content %}

{% load crispy_forms_tags %}

<div class="container py-5">
    {% if user.is_authenticated %}

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <h2>
            Temas de interés
        </h2>
        <p> Seleccione los temas de interés sobre los cuales quisiera ser notificado. Tan pronto se realice alguna publicación dentro de las categorías seleccionadas, le llegará una notificación. </p>

        {{ form|crispy }}

        <input type="submit" value="Save">
        <!-- <div class="form-check">
            {% for key, value in form.topics.field.choices %}
            <div>
                <input class="form-check-input" type="checkbox" id="id_feature_{{ key }}" value="{{key}}" name="topics">
                {% if value in user.topics %}
                <p>gaea</p>
                {% endif %}
                <label class="form-check-label" for="{{value}}">
                    {{ value }}
                </label>
            </div>
            {% endfor %}


        </div> -->
    </form>

    {% else %}
    <h1>

        <p>You are not logged in</p>
    </h1>
    {% endif %}
</div>

{% endblock %}

templates/header.html
<!DOCTYPE html>
<html>

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
    crossorigin="anonymous"></script>

  <!-- Google Fonts-->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link
    href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;300;400;500;900&family=Orbitron:wght@500&family=Ubuntu:wght@300;400;700&display=swap"
    rel="stylesheet">

  <!-- Font Awesome -->
  <script src="https://kit.fontawesome.com/886e1a7ae9.js" crossorigin="anonymous"></script>

  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">


  <title>{% block title %}Title{% endblock %}</title>
</head>

<body>
  {% block body %}
  <div class="container-fluid">
    <nav class="navbar navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'main:homepage' %}">FISI-NoS</a>

      {% if user.is_authenticated %}
      <div class="alert alert-primary p-3">
        ¡Bienvenido <strong>{{ user.username }}</strong>!
      </div>
      {% else %}
      <p class="text-white">You are not logged in</p>
      {% endif %}
      <form class="form-inline">
        {% if user.is_authenticated %}
        <a class="btn btn-outline-warning btn-sm" href="{% url 'main:profile' %}" role="button">Mi Perfil</a>
        <a class="btn btn-outline-warning btn-sm" href="{% url 'main:topics' %}" role="button">Temas de Interés</a>
        <a class="btn btn-secondary btn-sm" href="{% url 'account_email' %}" role="button">Cambiar e-mail</a>
        <a class="btn btn-danger btn-sm" href="{% url 'account_logout' %}" role="button">Salir</a>
        {% else %}
        <a class="btn btn-success btn-sm" href="{% url 'account_login' %}" role="button">Iniciar Sesión</a>
        <a class="btn btn-warning btn-sm" href="{% url 'account_signup' %}" role="button">Registrarse</a>
        {% endif %}
        </ul>
      </form>
    </nav>
  </div>

  <div class="container main-body border">
    {% if messages %}
    <div>
      <ul>
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}" role="alert">
          <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
        </div>
        {% endfor %}
      </ul>
    </div>
    {% endif %}
    {% endblock %}

    {% block content %}
    {% endblock %}
  </div>


</body>

</html>